# -*- coding: utf-8 -*-
"""Visualising Streaming Data with Streamlit II project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXSl6tTYI_URKq9m6IVQCudT_xXYZqMR
"""



"""
**Real-Time Telecom Fraud Detection Dashboard**
This project aims to build a real-time data visualization dashboard using Streamlit to monitor Reddit for mentions of telecom fraud and related keywords. By connecting to Reddit's API, collecting real-time posts, processing the data, and visualizing it, we can identify patterns and trends related to telecom fraud. The ultimate goal is to provide a tool that helps in detecting and preventing fraud in the telecommunications industry.

**Problem Statement**
Telecom fraud is a significant issue that causes substantial financial losses to the telecommunications industry. Fraudsters exploit weaknesses in telecom infrastructure, hack into phone systems, engage in identity theft, and manipulate billing systems. The challenge for telecom companies is to detect and prevent fraud in real-time, minimizing the financial impact.

**Project Overview**
The project involves the following steps:

**Reddit API Integration**: Connect to Reddit's API by setting up a developer account and creating an app to access the required data.

**Real-Time Data Collection**: Utilize the praw library to retrieve real-time posts related to telecom fraud and related keywords from Reddit. Collect important information such as post text, user name, subreddit, and date/time.

**Data Processing and Analysis**: Process the collected posts to extract valuable information, store it in a Pandas DataFrame, and analyze the data to identify patterns and trends related to telecom fraud.

**Interactive Data Visualization**: Use the Streamlit library to create an interactive data visualization dashboard. Present the analyzed data using intuitive charts and graphs, making it easier to identify insights and trends in real-time.

Dashboard Features
The real-time telecom fraud detection dashboard offers the following features:

**Real-Time Data**: The dashboard displays the latest posts related to telecom fraud fetched from Reddit's API. The data is continuously updated to provide real-time insights.

**Visualization**: Interactive charts and graphs provide visual representations of the collected data. Examples include bar charts showing the number of fraud mentions by subreddit and line charts depicting the frequency of fraud mentions over time.

**Filtering and Search**: Users can filter data based on specific criteria, such as subreddit, date, or keyword. A search functionality allows users to search for specific terms within the collected posts.

**User-Friendly Interface**: The dashboard is designed to be user-friendly, with clear labels, instructions, and intuitive navigation. It offers a seamless experience for users to explore the data and gain valuable insights.


**Conclusion**
The real-time telecom fraud detection dashboard offers a powerful tool for monitoring Reddit and analyzing data related to telecom fraud. By leveraging Streamlit and Reddit's API, it provides an intuitive and interactive visualization of fraud mentions, helping telecom companies detect and prevent fraud in real-time."""

import praw
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

# Reddit API credentials
client_id = 'VPbj6VyUBsWTlTTgnHI_gA'
client_secret = 'cRKLJidtF1_TwujJgpkxhcpAQ6200A'
user_agent = 'Chitechi_9130'

# Connect to Reddit API
reddit = praw.Reddit(client_id=client_id, client_secret=client_secret, user_agent=user_agent)

# Streamlit App
st.title("Telecom Fraud Visualization Dashboard")

# Function to collect recent posts
def collect_posts(keywords, limit=50):
    posts = []
    for keyword in keywords:
        subreddit = reddit.subreddit('all')
        subreddit_posts = subreddit.search(keyword, limit=limit)
        for post in subreddit_posts:
            posts.append([post.title, post.author.name, post.subreddit.display_name, post.created_utc])
    return posts

# Process the collected posts
def process_posts(posts):
    df = pd.DataFrame(posts, columns=['Title', 'Author', 'Subreddit', 'Timestamp'])
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='s')
    return df

# Analyze the data and create visualizations
def analyze_data(df):
    st.subheader("Fraud Mentions by Subreddit")
    subreddit_counts = df['Subreddit'].value_counts().head(10)
    st.bar_chart(subreddit_counts)

    st.subheader("Fraud Mentions Over Time")
    daily_counts = df.set_index('Timestamp').resample('D').size()
    st.line_chart(daily_counts)

# Main function to run the Streamlit app
def main():
    keywords = ['telecoms fraud', 'telecoms scam', 'phone fraud', 'billing fraud', 'identity theft']
    posts = collect_posts(keywords)
    df = process_posts(posts)
    st.title("Telecom Fraud Posts")
    st.dataframe(df)
    analyze_data(df)

if __name__ == '__main__':
    main()